#ifndef ROBOTROSGETSTARTEDEXAMPLE_EDIT__VISIBILITY_CONTROL_H_
#define ROBOTROSGETSTARTEDEXAMPLE_EDIT__VISIBILITY_CONTROL_H_
#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define ROBOTROSGETSTARTEDEXAMPLE_EDIT_EXPORT __attribute__ ((dllexport))
    #define ROBOTROSGETSTARTEDEXAMPLE_EDIT_IMPORT __attribute__ ((dllimport))
  #else
    #define ROBOTROSGETSTARTEDEXAMPLE_EDIT_EXPORT __declspec(dllexport)
    #define ROBOTROSGETSTARTEDEXAMPLE_EDIT_IMPORT __declspec(dllimport)
  #endif
  #ifdef ROBOTROSGETSTARTEDEXAMPLE_EDIT_BUILDING_LIBRARY
    #define ROBOTROSGETSTARTEDEXAMPLE_EDIT_PUBLIC ROBOTROSGETSTARTEDEXAMPLE_EDIT_EXPORT
  #else
    #define ROBOTROSGETSTARTEDEXAMPLE_EDIT_PUBLIC ROBOTROSGETSTARTEDEXAMPLE_EDIT_IMPORT
  #endif
  #define ROBOTROSGETSTARTEDEXAMPLE_EDIT_PUBLIC_TYPE ROBOTROSGETSTARTEDEXAMPLE_EDIT_PUBLIC
  #define ROBOTROSGETSTARTEDEXAMPLE_EDIT_LOCAL
#else
  #define ROBOTROSGETSTARTEDEXAMPLE_EDIT_EXPORT __attribute__ ((visibility("default")))
  #define ROBOTROSGETSTARTEDEXAMPLE_EDIT_IMPORT
  #if __GNUC__ >= 4
    #define ROBOTROSGETSTARTEDEXAMPLE_EDIT_PUBLIC __attribute__ ((visibility("default")))
    #define ROBOTROSGETSTARTEDEXAMPLE_EDIT_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define ROBOTROSGETSTARTEDEXAMPLE_EDIT_PUBLIC
    #define ROBOTROSGETSTARTEDEXAMPLE_EDIT_LOCAL
  #endif
  #define ROBOTROSGETSTARTEDEXAMPLE_EDIT_PUBLIC_TYPE
#endif
#endif  // ROBOTROSGETSTARTEDEXAMPLE_EDIT__VISIBILITY_CONTROL_H_
// Generated 16-Jun-2021 16:16:48
// Copyright 2019-2020 The MathWorks, Inc.
